### ISSUE TITLE
Remove Clamp from book image

### ISSUE THREAD

**Issue by 1208overlord** [sujaykhandekar/Automated-objects-removal-inpainter#1]
I am going to use this repository for my aim.
And then, is it possible to remove clamp clearly?
![Uploading IMG_000013.jpg…]()

**Comment by sujaykhandekar** [comment]
can you post the image of clamp again? it is not visible.

**Comment by 1208overlord** [comment]
![Uploading 2.jpg…]()

**Comment by 1208overlord** [comment]
![2](https://user-images.githubusercontent.com/51698017/102526995-d3c94600-40df-11eb-8c67-7d30744392e3.jpg)

**Comment by sujaykhandekar** [comment]
No it wont be possible to remove it with this tool. This tool can only  remove certain things such as car, birds etc.
For removing clamp you can use free image inpainting software online, they will do the job.

**Comment by 1208overlord** [comment]
Sorry, but if you know one url for it, could you please let me know?

**Comment by sujaykhandekar** [comment]
here you go!
https://theinpaint.com/
