### ISSUE TITLE
Can this model delete Chars (words) from image?

### ISSUE THREAD

**Issue by pnzr00t** [sujaykhandekar/Automated-objects-removal-inpainter#2]
Can this model delete Chars (words) from image?

**Comment by pnzr00t** [comment]
And 1 more questions. After running you models i get result always something like this (in any model settings )
![0090](https://user-images.githubusercontent.com/9987672/103178163-74aec280-4891-11eb-97a4-5c2e9cf329d7.jpg)

**Comment by pnzr00t** [comment]
> 
> 
> And 1 more questions. After running you models i get result always something like this (in any model settings )
> ![0090](https://user-images.githubusercontent.com/9987672/103178163-74aec280-4891-11eb-97a4-5c2e9cf329d7.jpg)

Find problem, i use bash script, they download Edge models, but not copy/move content of the folders

**Comment by sujaykhandekar** [comment]
Great!. yes that indeed must have been a problem. Seems like inpainting models weight were never used so it just replaced the gaps with random noise!.

**Comment by vineeth12365** [comment]
> > And 1 more questions. After running you models i get result always something like this (in any model settings )
> > ![0090](https://user-images.githubusercontent.com/9987672/103178163-74aec280-4891-11eb-97a4-5c2e9cf329d7.jpg)
> 
> Find problem, i use bash script, they download Edge models, but not copy/move content of the folders

same problem

**Comment by pnzr00t** [comment]
> same problem

Open bash script, manually download model (copy url from script), and move this file in right folder (look where it moving in bash script)
