### ISSUE TITLE
Not removing objects correctly

### ISSUE THREAD

**Issue by vineeth12365** [sujaykhandekar/Automated-objects-removal-inpainter#20]
![386_256](https://user-images.githubusercontent.com/105844068/169235884-9056e96d-7a72-45ac-844a-269a14f24fad.jpg)
![856_256](https://user-images.githubusercontent.com/105844068/169235893-25d97ec8-1a00-4aa8-83e5-923d637f7dd4.jpg)
![985_256](https://user-images.githubusercontent.com/105844068/169235898-09d0cb70-9aff-472f-9435-ed080b3fb8ce.jpg)
![1023_256](https://user-images.githubusercontent.com/105844068/169235904-93633e28-b229-4a32-9abd-77594dc3a92e.jpg)
![1055_256](https://user-images.githubusercontent.com/105844068/169235908-b8be9b42-b3bf-4608-915d-45d4cf154f49.jpg)
![0090](https://user-images.githubusercontent.com/105844068/169235910-0ac7ff0f-e58e-4bb4-bcd1-a2b5f6626af2.jpg)
![0095](https://user-images.githubusercontent.com/105844068/169235913-440d6ad1-e4bd-4c30-8060-f999983b8a3e.jpg)
![141_256](https://user-images.githubusercontent.com/105844068/169235916-7a8dad6e-5ee1-4c9d-8215-cc84212a8cb5.jpg)
![277_256](https://user-images.githubusercontent.com/105844068/169235921-d4868abb-6a16-4ef8-9b6b-ccf00ba2af81.jpg)
![292_256](https://user-images.githubusercontent.com/105844068/169235927-acd80120-1a16-442a-9064-dee527bd3423.jpg)
![313_256](https://user-images.githubusercontent.com/105844068/169235931-22da983f-ed23-414e-94cd-e30d3ce24476.jpg)
![0376](https://user-images.githubusercontent.com/105844068/169235932-af8c39dd-01fb-4d8d-9206-128d87427331.jpg)
![0378](https://user-images.githubusercontent.com/105844068/169235933-c89d9c71-7a46-44f4-b0eb-6b9578b0feae.jpg)

**Comment by vineeth12365** [comment]
not at all removing properly

**Comment by vineeth12365** [comment]
can U guide me to ,how to remove properly

**Comment by sujaykhandekar** [comment]
@vineeth12365 this happens when pre trained Edge connect models are not configured properly. Please check this https://github.com/knazeri/edge-connect
Use the links for the pretrained models from that repo, if the one mentioned on mine are not working.

**Comment by ocissor** [comment]
Hi, @sujaykhandekar I am also getting results like @vineeth12365. Can anyone tell me what should i change in the config file to get the correct results?

Thank you
