### ISSUE TITLE
Not removing objects properly

### ISSUE THREAD

**Issue by vineeth12365** [sujaykhandekar/Automated-objects-removal-inpainter#21]
![386_256](https://user-images.githubusercontent.com/105844068/169236460-d979f9b5-2d82-49c1-9a2b-564d452e6c35.jpg)
![856_256](https://user-images.githubusercontent.com/105844068/169236465-f02e1b01-d0e4-4511-8a56-37540c4eaf54.jpg)
![985_256](https://user-images.githubusercontent.com/105844068/169236467-0b8e13aa-2ff4-4885-8517-b85c27274955.jpg)
![1023_256](https://user-images.githubusercontent.com/105844068/169236469-9ee162ae-8d59-4e55-ad88-5219c43f3e38.jpg)
![1055_256](https://user-images.githubusercontent.com/105844068/169236470-a8f91366-fe3d-4c6e-8af7-f4e340079487.jpg)
![0090](https://user-images.githubusercontent.com/105844068/169236471-79100ce6-d375-4005-b5ce-779e82da83d9.jpg)
![0095](https://user-images.githubusercontent.com/105844068/169236472-c883d33a-8436-48db-a9ec-2522e12e71cf.jpg)
![141_256](https://user-images.githubusercontent.com/105844068/169236473-3ce19c63-864f-4db3-b3c5-88228ddb3a7b.jpg)
![277_256](https://user-images.githubusercontent.com/105844068/169236477-97221f1b-180a-4162-a75d-a1198dad96cd.jpg)
![292_256](https://user-images.githubusercontent.com/105844068/169236479-4a34004d-fff9-488b-a5e7-9b56b3d5a766.jpg)
![313_256](https://user-images.githubusercontent.com/105844068/169236483-aa620012-cb8a-454d-a402-ef04f5cf8fe1.jpg)
![0376](https://user-images.githubusercontent.com/105844068/169236484-d5e1c883-d79e-4ea8-ae16-2cc1a435d1d7.jpg)
![0378](https://user-images.githubusercontent.com/105844068/169236490-c57054d3-9426-41aa-a748-0edba7cdceeb.jpg)

Can U guide me to ,how to remove properly?

**Comment by sujaykhandekar** [comment]
duplicate

**Comment by ocissor** [comment]
Hi @sujaykhandekar what do you mean by duplicate?

Thank you
